language: node_js

node_js:
  - iojs

script:
  - npm run lint
  - npm test
  - npm run coveralls
  - npm run deploy

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
